# Default Configuration
# This serves as a fallback when no environment-specific config is found
# For production use, set ENVIRONMENT=prod to use config-prod.yaml

server:
  port: 8000
  host: 0.0.0.0

mcp:
  datawarehouse_url: http://localhost:6000/sse
  rag_url: http://localhost:6001/sse
  geospatial_url: http://localhost:6002/sse
  # For deployment
  # datawarehouse_url: http://datawarehouse_mcp:6000/sse
  # rag_url: http://rag_mcp:6001/sse
  # geospatial_url: http://geospatial_mcp:6002/sse

llm:
  # model: "gpt-4.1"
  # model: "gemini-2.5-pro"
  model: "bedrock/arn:aws:bedrock:us-east-2:669072008720:inference-profile/us.anthropic.claude-sonnet-4-20250514-v1:0"
  temperature: 0.0
