server:
  port: 8000
  host: 0.0.0.0

mcp:
  datawarehouse_url: http://datawarehouse_mcp:6000/sse
  rag_url: http://rag_mcp:6001/sse
  geospatial_url: http://geospatial_mcp:6002/sse

llm:
  model: "gpt-4.1"
  temperature: 0.0
