# Production Configuration
# Used when ENVIRONMENT=prod

server:
  port: 8000
  host: 0.0.0.0

mcp:
  # Docker service names for production deployment
  datawarehouse_url: http://datawarehouse_mcp:6000/sse
  rag_url: http://rag_mcp:6001/sse
  geospatial_url: http://geospatial_mcp:6002/sse

llm:
  # model: "gpt-4.1"
  # model: "gemini-2.5-pro"
  model: "bedrock/arn:aws:bedrock:us-east-1:505646497781:inference-profile/us.anthropic.claude-sonnet-4-20250514-v1:0"
  temperature: 0.0
  provider: "bedrock"
